### ISSUE TITLE
Figure out best way to navigation to multiple education pages

### ISSUE THREAD

**Issue by edalzell** [VegasHC/eileen200#36]
Options:

1) Nav menu drop down?
2) separate page that lists them?

**Comment by edalzell** [comment]
@VegasHC check out staging, you'll see a new `Education` collection, moved all your draft ones there. Also updated the menu.

Just need to work through some styling things...do we want cards here with some kind of image like we do w/ articles?

**Comment by VegasHC** [comment]
Hi Erin,

It's great! I looked at it with Diego and that's what he wanted.  No need for them to have some kind of image. 
One thing I noticed when I published another education page was that they became next to each other instead of going downwards like a list.
![image](https://user-images.githubusercontent.com/98860212/231849701-31daf8e4-14ac-4fb7-8202-1f0cc7180e94.png)

**Comment by VegasHC** [comment]
Also is there any way to have the "Education" title part go in the middle of the page instead of the left?

**Comment by edalzell** [comment]
> Also is there any way to have the "Education" title part go in the middle of the page instead of the left?

This is on staging for you to take a look. Not sure if you like the `*` (dot) for the listing, and if they should be in the middle of the page too?

**Comment by VegasHC** [comment]
Awesome, thank you! I'll review it Diego today and see what he thinks!

**Comment by edalzell** [comment]
> Awesome, thank you! I'll review it Diego today and see what he thinks!

@VegasHC you want me to deploy this to the site Mauricio?

**Comment by VegasHC** [comment]
Yes please, go ahead!
